config/routes.rb
Rails.application.routes.draw do
  devise_for :patients
	root to: "doctors#index"

	resources :doctors
	resources :appointments
	resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient

  validates :appointment_date, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :patients, through: :appointments

	validates :username, :address, :specialty, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [:password, :password_confirmation, :current_password]
    )
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_patient!
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all
    @appointment = current_patient.appointments.new
  end

  def new
    @appointment = Appointment.new
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.patient = current_patient

    if @appointment.save
      redirect_to action: :index, notice: 'Appointment was successfully created.'
    else
      render :index
    end
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_url, notice: 'Appointment was successfully destroyed.'
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:appointment_date)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_patient!
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor, notice: 'Doctor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_url, notice: 'Doctor was successfully destroyed.'
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:username, :address, :specialty)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: appointment} %>

  <div class="form-group">
   <%= form.label :patient_id %>
   <%= form_field :patient_id %>
  </div>

  <div class="form-group">
   <%= form.label :doctor_id %>
   <%= form.select :doctor_id, @doctors.map { |d| [d.username, d.id]} %>
  </div>

  <div class="form-group">
   <%= form.label :doctor_id.specialty %>
   <%= form_field :doctor_id.specialty %>
  </div>

  <div class="form-group">
   <%= form.label :appointment_date %>
   <%= form_field :appointment_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>
<br>
<h3>Schedule: 09.00 - 18.00</h3>
<h4>Break-time: 13.00 - 14.00</h4>

<table class="table table-boardered">
  <thead>
    <tr>
      <th scope="col">Patient</th>
      <th scope="col">Doctor</th>
      <th scope="col">Specialty</th>
      <th scope="col">Date</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.inspect %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Order Appointment', new_appointment_path, class: 'btn btn-primary' %>

<%= link_to 'Back', root_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: @doctor} %>

<div class="form-group">
    <%= form.label :username %><br />
    <%= form.text_field :username, autofocus: true %>
  </div>

  <div class="form-group">
    <%= form.label :specialty %><br />
    <%= form.text_field :specialty %>
  </div>

  <div class="form-group">
    <%= form.label :address %><br />
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Specialty</th>
      <th scope="col">Address</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.username %> </td>
        <td><%= doctor.specialty %> </td>
        <td><%= doctor.address %> </td>
        <td><%= link_to 'Appoint', appointments_path, class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hospital" %></title>
    <link data-require="bootstrap@*" data-semver="4.1.3" rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <script data-require="bootstrap@*" data-semver="4.1.3" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script data-require="jquery@*" data-semver="3.2.1" src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="header-logo">
          <%= link_to 'Clinica Pupkin', root_path, class: 'navbar-brand' %>
        </div>
        <div class="header-nav">
          <% if patient_signed_in? %>
            <%= "@#{current_patient.username}" %>
            <%= link_to 'Sign out', destroy_patient_session_path, :method => :delete  %>
          <% else %>
            <%= link_to 'Sign up', new_patient_registration_path %>
            <%= link_to 'Sign in', new_patient_session_path %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>  
      <footer>
        <p>&copy; <%=  'Будущий программист' %> 2019</p>
      </footer>
    </div>
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>

<% if errors.any? %>
  <div class="alert alert-danger">
    <div class="lead buffer-bottom">
      In your form <%= errors.count %> error(s)
    </div>

    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>